#!/usr/bin/env python3
"""Stage the supplementary tables that are not produced by the screen or the simulation.

Every released table now has a generator. Two of them (the cohort registry and the
hyperparameter list) are maintained by hand and live in supplementary_src/; the other
two are assembled here from analysis outputs. Nothing is copied into supplementary/
by hand any more - a table number changed twice during revision and hand copies drifted.
"""
from pathlib import Path
import shutil
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
SUP = ROOT / "supplementary"
SRC = ROOT / "supplementary_src"
SUP.mkdir(exist_ok=True)

# ---- S4: learned pooling -----------------------------------------------------
met = pd.read_csv(ROOT / "data/legacy/learned_pooling_metrics.tsv", sep="\t")
pair = pd.read_csv(ROOT / "data/legacy/learned_pooling_paired_tests.tsv", sep="\t")
out4 = SUP / "Table_S6_learned_pooling.tsv"
with out4.open("w") as fh:
    fh.write("# Part 1: per-method target metrics, both transfer directions.\n")
    met.to_csv(fh, sep="\t", index=False)
    fh.write("\n# Part 2: paired DeLong tests against each baseline, with\n")
    fh.write("# Benjamini-Hochberg q-values computed inside each declared family.\n")
    pair.to_csv(fh, sep="\t", index=False)

# ---- S9: decision-tree walkthrough ------------------------------------------
wt = pd.read_csv(ROOT / "walkthrough/results/decision_tree_walkthrough.tsv", sep="\t")
out9 = SUP / "Table_S7_decision_tree_walkthrough.tsv"
wt.to_csv(out9, sep="\t", index=False)

# ---- S5, S7: hand-maintained sources ----------------------------------------
# The registry is generated by tools/build_registry_table.py; only the
# hyperparameter list is still maintained by hand.
copies = {"hyperparameters.tsv": "Table_S10_hyperparameters.tsv"}
for src, dst in copies.items():
    shutil.copyfile(SRC / src, SUP / dst)

for f in (out4, out9, SUP / "Table_S10_hyperparameters.tsv"):
    print(f"wrote {f.relative_to(ROOT)}  ({f.stat().st_size} bytes)")
